/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yj_ffmpegvideo_FFMPEG */

#ifndef _Included_cn_yj_ffmpegvideo_FFMPEG
#define _Included_cn_yj_ffmpegvideo_FFMPEG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yj_ffmpegvideo_FFMPEG
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_yj_ffmpegvideo_FFMPEG_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
